const threadTypes= {
    FETCH_THREADS_START: 'FETCH_THREADS_START',
    FETCH_THREADS_SUCCESS: 'FETCH_THREADS_SUCCESS',
    FETCH_THREAD_SUCCESS: 'FETCH_THREAD_SUCCESS',
    FETCH_THREADS_FAILURE: 'FETCH_THREADS_FAILURE',

    CREATE_THREAD_START: 'CREATE_THREAD_START',
    CREATE_THREAD_SUCCESS: 'CREATE_THREAD_SUCCESS',
    CREATE_THREAD_FAILURE: 'CREATE_THREAD_FAILURE',

    CREATE_POST_START: 'CREATE_POST_START',
    CREATE_POST_SUCCESS: 'CREATE_POST_SUCCESS',
    CREATE_POST_FAILURE: 'CREATE_POST_FAILURE',

    CLEAR_UPLOAD_MESSAGE: 'CLEAR_UPLOAD_MESSAGE',
    CLEAR_CURRENT_THREAD: 'CLEAR_CURRENT_THREAD',

    LIKE_DISLIKE_START: 'LIKE_DISLIKE_START',
    LIKE_DISLIKE_SUCCESS: 'LIKE_DISLIKE_SUCCESS',
    LIKE_DISLIKE_FAILURE: 'LIKE_DISLIKE_FAILURE'
}

export default threadTypes