const threadTypes= {
    FETCH_THREADS_START: 'FETCH_THREADS_START',
    FETCH_THREADS_SUCCESS: 'FETCH_THREADS_SUCCESS',
    FETCH_THREADS_FAILURE: 'FETCH_THREADS_FAILURE'
}

export default threadTypes