const UserActionTypes= {

    GET_USER_FROM_COOKIE_START: 'GET_USER_FROM_COOKIE_START',
    GET_USER_FROM_COOKIE_SUCCESS: 'GET_USER_FROM_COOKIE_SUCCESS',
    GET_USER_FROM_COOKIE_FAILURE: 'GET_USER_FROM_COOKIE_FAILURE',

    SIGN_IN_START: 'SIGN_IN_START',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',

    SIGN_OUT_START: 'SIGN_OUT_START',
    SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
    SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',

    SIGN_UP_START: 'SIGN_OUT_START',
    SIGN_UP_SUCCESS: 'SIGN_OUT_SUCCESS',
    SIGN_UP_FAILURE: 'SIGN_OUT_FAILURE',

    UPDATE_USER_NAME_START: 'UPDATE_USER_NAME_START',
    UPDATE_USER_NAME_SUCCESS: 'UPDATE_USER_NAME_SUCCESS',
    UPDATE_USER_NAME_FAILURE: 'UPDATE_USER_NAME_FAILURE',

    UPDATE_USER_EMAIL_START: 'UPDATE_USER_EMAIL_START',
    UPDATE_USER_EMAIL_SUCCESS: 'UPDATE_USER_EMAIL_SUCCESS',
    UPDATE_USER_EMAIL_FAILURE: 'UPDATE_USER_EMAIL_FAILURE',

    UPDATE_USER_PASSWORD_START: 'UPDATE_USER_PASSWORD_START',
    UPDATE_USER_PASSWORD_SUCCESS: 'UPDATE_USER_PASSWORD_SUCCESS',
    UPDATE_USER_PASSWORD_FAILURE: 'UPDATE_USER_PASSWORD_FAILURE',

    FORGOT_USER_PASSWORD_START: 'FORGOT_USER_PASSWORD_START',
    FORGOT_USER_PASSWORD_SUCCESS: 'FORGOT_USER_PASSWORD_SUCCESS',
    FORGOT_USER_PASSWORD_FAILURE: 'FORGOT_USER_PASSWORD_FAILURE'

}

export default UserActionTypes