const UserActionTypes= {
    GET_USER_FROM_COOKIE_START: 'GET_USER_FROM_COOKIE_START',
    GET_USER_FROM_COOKIE_SUCCESS: 'GET_USER_FROM_COOKIE_SUCCESS',
    GET_USER_FROM_COOKIE_FAILURE: 'GET_USER_FROM_COOKIE_FAILURE',

    SIGN_IN_START: 'SIGN_IN_START',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',

    SIGN_OUT_START: 'SIGN_OUT_START',
    SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
    SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',

    SIGN_UP_START: 'SIGN_OUT_START',
    SIGN_UP_SUCCESS: 'SIGN_OUT_SUCCESS',
    SIGN_UP_FAILURE: 'SIGN_OUT_FAILURE',

    UPDATE_USER_DATA_START: 'UPDATE_USER_DATA_START',
    UPDATE_USER_DATA_SUCCESS: 'UPDATE_USER_DATA_SUCCESS',
    UPDATE_USER_DATA_FAILURE: 'UPDATE_USER_DATA_FAILURE',

    FORGOT_USER_PASSWORD_START: 'FORGOT_USER_PASSWORD_START',
    FORGOT_USER_PASSWORD_SUCCESS: 'FORGOT_USER_PASSWORD_SUCCESS',
    FORGOT_USER_PASSWORD_FAILURE: 'FORGOT_USER_PASSWORD_FAILURE',

    RESET_USER_PASSWORD_START: 'RESET_USER_PASSWORD_START',
    RESET_USER_PASSWORD_SUCCESS: 'RESET_USER_PASSWORD_SUCCESS',
    RESET_USER_PASSWORD_FAILURE: 'RESET_USER_PASSWORD_FAILURE',

    CLEAR_SUCCESS_MESSAGES: 'CLEAR_SUCCESS_MESSAGES',
    CLEAR_ERROR_MESSAGES: 'CLEAR_ERROR_MESSAGES',

    SEND_TOKEN_START: 'SEND_TOKEN_START',
    SEND_TOKEN_SUCCESS: 'SEND_TOKEN_SUCCESS',
    SEND_TOKEN_FAILURE: 'SEND_TOKEN_FAILURE',

    CLEAR_TOKEN: 'CLEAR_TOKEN'
}

export default UserActionTypes